export const PACKAGES = [
  // Scoped @bam.tech packages
  '@bam.tech/react-native-image-resizer',
  '@bam.tech/react-navigation-visualizer-dev-plugin',
  '@bam.tech/react-native-app-security',
  '@bam.tech/react-native-make',
  '@bam.tech/eslint-plugin',
  '@bam.tech/react-native-config',
  '@bam.tech/react-native-keyevent-expo-config-plugin',
  '@bam.tech/lrud',
  '@bam.tech/flow-navigator',
  '@bam.tech/react-native-graphql-transformer',
  '@bam.tech/tanstack-query-detect-waterfall',
  '@bam.tech/react-native-batch',
  // Unscoped packages
  'react-native-performance',
  'react-native-image-resizer',
  'react-native-hide-with-keyboard',
  'react-native-image-header-scroll-view',
  'generator-rn-toolbox',
  'react-native-make',
  'redux-enhancer-react-native-appstate',
  'react-tv-space-navigation',
  'react-native-formik',
  'rn-camera-roll',
  'react-native-braintree-payments-drop-in',
  'react-native-form-idable',
  'react-redux-toolbox',
  'react-native-debugger-utils',
  'redux-async-actions-factory',
  'react-native-photo-guideline-grid',
  'generator-module-react-native',
  'devicelab-bot',
  'react-native-numberpicker-dialog',
  'cordova-camera-roll',
  'react-native-text-input',
] as const;

export type PackageName = (typeof PACKAGES)[number];
